require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'UpgradeProject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'UpgradeProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({
    "Flipper" => "0.134.0",
    "Flipper-Folly" => "2.6.10",
    "OpenSSL-Universal" => "1.1.1100"
   })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'UpgradeProject-tvOS' do
  # Pods for UpgradeProject-tvOS

  target 'UpgradeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
